name: Tests
on:
    push:

tests:
    my_build_tests:
      runs-on: ubuntu-latest
         - name: Run Unittests
         run: python -m unittest unittests.py
         
      runs-on: windows-latest
          - name: Run Unittests
            run: python -m unittest unittests.py
